// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $api_callback from "./routes/api/callback.ts"
import * as $api_login from "./routes/api/login.ts"
import * as $api_logout from "./routes/api/logout.ts"
import * as $dashboard from "./routes/dashboard.tsx"
import * as $greet_name_ from "./routes/greet/[name].tsx"
import * as $index from "./routes/index.tsx"
import * as $login from "./routes/login.tsx"
import * as $Button from "./islands/Button.tsx"
import * as $Footer from "./islands/Footer.tsx"
import * as $LoginBox from "./islands/LoginBox.tsx"
import * as $Navbar from "./islands/Navbar.tsx"
import * as $TranslationContext from "./islands/TranslationContext.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/api/callback.ts": $api_callback,
		"./routes/api/login.ts": $api_login,
		"./routes/api/logout.ts": $api_logout,
		"./routes/dashboard.tsx": $dashboard,
		"./routes/greet/[name].tsx": $greet_name_,
		"./routes/index.tsx": $index,
		"./routes/login.tsx": $login,
	},
	islands: {
		"./islands/Button.tsx": $Button,
		"./islands/Footer.tsx": $Footer,
		"./islands/LoginBox.tsx": $LoginBox,
		"./islands/Navbar.tsx": $Navbar,
		"./islands/TranslationContext.tsx": $TranslationContext,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
