// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx"
import * as $_app from "./routes/_app.tsx"
import * as $_middleware from "./routes/_middleware.ts"
import * as $api_callback from "./routes/api/callback.ts"
import * as $api_login_email from "./routes/api/login/email.ts"
import * as $api_login_index from "./routes/api/login/index.ts"
import * as $api_logout from "./routes/api/logout.ts"
import * as $api_schools from "./routes/api/schools.ts"
import * as $api_signup from "./routes/api/signup.tsx"
import * as $dashboard from "./routes/dashboard.tsx"
import * as $greet_name_ from "./routes/greet/[name].tsx"
import * as $index from "./routes/index.tsx"
import * as $login from "./routes/login.tsx"
import * as $schools_id_ from "./routes/schools/[id].tsx"
import * as $schools_index from "./routes/schools/index.tsx"
import * as $signup from "./routes/signup.tsx"
import * as $Button from "./islands/Button.tsx"
import * as $CreateSchool from "./islands/CreateSchool.tsx"
import * as $Error404 from "./islands/Error404.tsx"
import * as $Footer from "./islands/Footer.tsx"
import * as $LoginBox from "./islands/LoginBox.tsx"
import * as $Main from "./islands/Main.tsx"
import * as $Navbar from "./islands/Navbar.tsx"
import * as $SignupBox from "./islands/SignupBox.tsx"
import * as $TranslationContext from "./islands/TranslationContext.tsx"
import type { Manifest } from "$fresh/server.ts"

const manifest = {
	routes: {
		"./routes/_404.tsx": $_404,
		"./routes/_app.tsx": $_app,
		"./routes/_middleware.ts": $_middleware,
		"./routes/api/callback.ts": $api_callback,
		"./routes/api/login/email.ts": $api_login_email,
		"./routes/api/login/index.ts": $api_login_index,
		"./routes/api/logout.ts": $api_logout,
		"./routes/api/schools.ts": $api_schools,
		"./routes/api/signup.tsx": $api_signup,
		"./routes/dashboard.tsx": $dashboard,
		"./routes/greet/[name].tsx": $greet_name_,
		"./routes/index.tsx": $index,
		"./routes/login.tsx": $login,
		"./routes/schools/[id].tsx": $schools_id_,
		"./routes/schools/index.tsx": $schools_index,
		"./routes/signup.tsx": $signup,
	},
	islands: {
		"./islands/Button.tsx": $Button,
		"./islands/CreateSchool.tsx": $CreateSchool,
		"./islands/Error404.tsx": $Error404,
		"./islands/Footer.tsx": $Footer,
		"./islands/LoginBox.tsx": $LoginBox,
		"./islands/Main.tsx": $Main,
		"./islands/Navbar.tsx": $Navbar,
		"./islands/SignupBox.tsx": $SignupBox,
		"./islands/TranslationContext.tsx": $TranslationContext,
	},
	baseUrl: import.meta.url,
} satisfies Manifest

export default manifest
