DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS schools CASCADE;
DROP TABLE IF EXISTS org_school CASCADE;
DROP TABLE IF EXISTS lecture CASCADE;
DROP TABLE IF EXISTS class CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS employee_school CASCADE;
DROP TABLE IF EXISTS lecture_employee CASCADE;
DROP TABLE IF EXISTS student_lecture CASCADE;
DROP TABLE IF EXISTS student_class CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS person_role CASCADE;

CREATE TABLE organization (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(250) NOT NULL UNIQUE);

CREATE TABLE class (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL);

CREATE TABLE subject (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE role (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE people (
id VARCHAR(36) PRIMARY KEY NOT NULL,
name VARCHAR(250) NOT NULL,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password_hash varchar,
cpf VARCHAR(20) UNIQUE,
google_picture VARCHAR,
created_at TIMESTAMP DEFAULT now());

CREATE TABLE schools (
id VARCHAR(36) PRIMARY KEY NOT NULL,
cnpj VARCHAR(20) UNIQUE,
name VARCHAR(250),
owner_id VARCHAR(36) NOT NULL,
created_at TIMESTAMP DEFAULT now(),
FOREIGN KEY(owner_id) REFERENCES people(id));

CREATE TABLE org_school (
organization INTEGER NOT NULL,
school VARCHAR(36) NOT NULL,
FOREIGN KEY(organization) REFERENCES organization(id),
FOREIGN KEY(school) REFERENCES schools(id));

CREATE TABLE lecture (
id INTEGER PRIMARY KEY NOT NULL,
subject INTEGER NOT NULL,
school VARCHAR(36) NOT NULL,
start_time TIMESTAMP NOT NULL,
end_time TIMESTAMP NOT NULL,
FOREIGN KEY(subject) REFERENCES subject(id),
FOREIGN KEY(school) REFERENCES schools(id));

CREATE TABLE employee_school (
school VARCHAR(36) NOT NULL,
employee VARCHAR(36) NOT NULL,
FOREIGN KEY(school) REFERENCES schools(id),
FOREIGN KEY(employee) REFERENCES people(id));

CREATE TABLE lecture_employee (
lecture INTEGER NOT NULL,
employee VARCHAR(36) NOT NULL,
FOREIGN KEY(lecture) REFERENCES lecture(id),
FOREIGN KEY(employee ) REFERENCES people(id));

CREATE TABLE student_lecture (
lecture integer NOT NULL,
student VARCHAR(36) NOT NULL,
FOREIGN KEY(lecture ) REFERENCES lecture(id),
FOREIGN KEY(student) REFERENCES people(id));

CREATE TABLE student_class (
student VARCHAR(36) NOT NULL,
class INTEGER NOT NULL,
joined TIMESTAMP NOT NULL,
departed TIMESTAMP,
FOREIGN KEY(student) REFERENCES people(id),
FOREIGN KEY(class) REFERENCES class(id));

CREATE TABLE person_role (
id INTEGER PRIMARY KEY NOT NULL,
person VARCHAR(36) NOT NULL,
role INTEGER NOT NULL,
enrolled TIMESTAMP NOT NULL,
unenrolled TIMESTAMP NOT NULL,
FOREIGN KEY(person) REFERENCES people(id),
FOREIGN KEY(role) REFERENCES role(id));
