DROP TABLE IF EXISTS organization;
DROP TABLE IF EXISTS school;
DROP TABLE IF EXISTS org_school;
DROP TABLE IF EXISTS lecture;
DROP TABLE IF EXISTS class;
DROP TABLE IF EXISTS subject;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS employee_school;
DROP TABLE IF EXISTS lecture_employee;
DROP TABLE IF EXISTS student_lecture;
DROP TABLE IF EXISTS student_class;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS person_role;

CREATE TABLE organization (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(250) NOT NULL UNIQUE);

CREATE TABLE class (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(50) NOT NULL);

CREATE TABLE subject (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE role (
id INTEGER PRIMARY KEY NOT NULL,
name VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE person (
id VARCHAR(20) PRIMARY KEY NOT NULL,
name VARCHAR(250) NOT NULL,
username VARCHAR(50) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
password_hash INTEGER NOT NULL,
cpf VARCHAR(20) NOT NULL UNIQUE,
google_picture VARCHAR,
created_at TIMESTAMP NOT NULL);

CREATE TABLE school (
id INTEGER PRIMARY KEY NOT NULL,
cnpj VARCHAR(20) NOT NULL UNIQUE,
name VARCHAR(250) NOT NULL UNIQUE,
owner_id VARCHAR(20) NOT NULL,
created_at TIMESTAMP NOT NULL,
FOREIGN KEY(owner_id) REFERENCES person(id));

CREATE TABLE org_school (
organization INTEGER NOT NULL,
school VARCHAR(20) NOT NULL,
FOREIGN KEY(organization) REFERENCES organization(id),
FOREIGN KEY(school) REFERENCES school(cnpj));

CREATE TABLE lecture (
id INTEGER PRIMARY KEY NOT NULL,
subject INTEGER NOT NULL,
school VARCHAR(20) NOT NULL,
start_time TIMESTAMP NOT NULL,
end_time TIMESTAMP NOT NULL,
FOREIGN KEY(subject) REFERENCES subject(id),
FOREIGN KEY(school) REFERENCES school(cnpj));

CREATE TABLE employee_school (
school VARCHAR(20) NOT NULL,
employee VARCHAR(20) NOT NULL,
FOREIGN KEY(school) REFERENCES school(cnpj),
FOREIGN KEY(employee) REFERENCES person(id));

CREATE TABLE lecture_employee (
lecture INTEGER NOT NULL,
employee  VARCHAR(20) NOT NULL,
FOREIGN KEY(lecture) REFERENCES lecture(id),
FOREIGN KEY(employee ) REFERENCES person(id));

CREATE TABLE student_lecture (
lecture integer NOT NULL,
student VARCHAR(20) NOT NULL,
FOREIGN KEY(lecture ) REFERENCES lecture(id),
FOREIGN KEY(student) REFERENCES person(id));

CREATE TABLE student_class (
student VARCHAR(20) NOT NULL,
class INTEGER NOT NULL,
joined TIMESTAMP NOT NULL,
departed TIMESTAMP,
FOREIGN KEY(student) REFERENCES person(id),
FOREIGN KEY(class) REFERENCES class(id));

CREATE TABLE person_role (
id INTEGER PRIMARY KEY NOT NULL,
person VARCHAR(20) NOT NULL,
role INTEGER NOT NULL,
enrolled TIMESTAMP NOT NULL,
unenrolled TIMESTAMP NOT NULL,
FOREIGN KEY(person) REFERENCES person(id),
FOREIGN KEY(role) REFERENCES role(id));
