export const logError = (error: any, message = "") => {
	// if(error instanceof Deno.errors.AddrInUse)
	//     console.error('AddrInUse: ' + message || error.message)
	// else if(error instanceof Deno.errors.AddrNotAvailable)
	//     console.error('AddrNotAvailable: ' + message || error.message)
	// else if(error instanceof Deno.errors.AlreadyExists)
	//     console.error('AlreadyExists: ' + message || error.message)
	// else if(error instanceof Deno.errors.BadResource)
	//     console.error('BadResource: ' + message || error.message)
	// else if(error instanceof Deno.errors.BrokenPipe)
	//     console.error('BrokenPipe: ' + message || error.message)
	// else if(error instanceof Deno.errors.Busy)
	//     console.error('Busy: ' + message || error.message)
	// else if(error instanceof Deno.errors.ConnectionAborted)
	//     console.error('ConnectionAborted: ' + message || error.message)
	// else if(error instanceof Deno.errors.ConnectionRefused)
	//     console.error('ConnectionRefused: ' + message || error.message)
	// else if(error instanceof Deno.errors.ConnectionReset)
	//     console.error('ConnectionReset: ' + message || error.message)
	// else if(error instanceof Deno.errors.FilesystemLoop)
	//     console.error('FilesystemLoop: ' + message || error.message)
	// else if(error instanceof Deno.errors.Http)
	//     console.error('Http: ' + message || error.message)
	// else if(error instanceof Deno.errors.Interrupted)
	//     console.error('Interrupted: ' + message || error.message)
	// else if(error instanceof Deno.errors.InvalidData)
	//     console.error('InvalidData: ' + message || error.message)
	// else if(error instanceof Deno.errors.IsADirectory)
	//     console.error('IsADirectory: ' + message || error.message)
	// else if(error instanceof Deno.errors.NetworkUnreachable)
	//     console.error('NetworkUnreachable: ' + message || error.message)
	// else if(error instanceof Deno.errors.NotADirectory)
	//     console.error('NotADirectory: ' + message || error.message)
	// else if(error instanceof Deno.errors.NotCapable)
	//     console.error('NotCapable: ' + message || error.message)
	// else if(error instanceof Deno.errors.NotConnected)
	//     console.error('NotConnected: ' + message || error.message)
	// else if(error instanceof Deno.errors.NotFound)
	//     console.error('NotFound: ' + message || error.message)
	// else if(error instanceof Deno.errors.NotSupported)
	//     console.error('NotSupported: ' + message || error.message)
	// else if(error instanceof Deno.errors.PermissionDenied)
	//     console.error('PermissionDenied: ' + message || error.message)
	// else if(error instanceof Deno.errors.TimedOut)
	//     console.error('TimedOut: ' + message || error.message)
	// else if(error instanceof Deno.errors.UnexpectedEof)
	//     console.error('UnexpectedEof: ' + message || error.message)
	// else if(error instanceof Deno.errors.WouldBlock)
	//     console.error('WouldBlock: ' + message || error.message)
	// else if(error instanceof Deno.errors.WriteZero)
	//     console.error('WriteZero: ' + message || error.message)
	// else console.error(`${error.name}: ${error.message}`)

	console.error(`${error.name}: ${error.message}`)
}
